### ISSUE TITLE
Frontend assets deploy is throwing errors

### ISSUE THREAD

**Issue by NagyWesley** [maxkostinevich/Shopify-Serverless-Starter-App#1]
running: `sls client deploy --no-delete-contents`
 throws this error
```
  Serverless Error --------------------------------------- 
  Serverless command "client" not found. Did you mean "list"? Run "serverless help" for a list of all available commands.
```
I think [serverless-finch](https://github.com/fernando-mc/serverless-finch) is missing, however, it is missing some config and the /dist folder so I'm not sure

**Comment by maxkostinevich** [comment]
Serverless-finch is not included, as it is not required, because all assets - css and js files are served by lambda function. After you install serverless-finch, this command should work.

**Comment by NagyWesley** [comment]
sorry for the late response. however, I've installed serverless-finch as development dependcy but it required `client/dist` and index.html... any help with that!?

**Comment by maxkostinevich** [comment]
@NagyWesley Please, read the documentation for serverless-finch. You need to specify **distributionFolder** as shown below:
`distributionFolder: public`
