### ISSUE TITLE
missing script: sls-client-deploy

### ISSUE THREAD

**Issue by tvb** [maxkostinevich/Shopify-Serverless-Starter-App#3]
From your readme:
```
% npm run sls-client-deploy
npm ERR! missing script: sls-client-deploy
```

**Comment by maxkostinevich** [comment]
@tvb Just install https://github.com/fernando-mc/serverless-finch

**Comment by tvb** [comment]
@maxkostinevich I figured, can you please update the serverless.yml file to include the custom/client parameters. Thanks!

**Comment by maxkostinevich** [comment]
This client is optional, and not required.

**Comment by tvb** [comment]
I see. Well for your convinience you could update the readme as it seems I am the second one asking this question 😉
