### ISSUE TITLE
Cannot read property 'name' of undefined in auth.js

### ISSUE THREAD

**Issue by tvb** [maxkostinevich/Shopify-Serverless-Starter-App#4]
Hi @maxkostinevich,

Sorry for bothering you again. Are you sure

https://github.com/maxkostinevich/Shopify-Serverless-Starter-App#shopify-app-setup 

is correct? When I click to install my application in my development shop I get the following error:
```
    "stack": [
        "TypeError: Cannot read property 'name' of undefined",
        "    at Response.dynamoDb.query (/var/task/app/auth.js:45:35)",
```

The /dev/install/store callback is never called.

**Comment by tvb** [comment]
The url being called when installing the app:

```
https://xxxx.execute-api.us-east-1.amazonaws.com/dev?hmac=xxxxxxx&shop=my-dev-shop.myshopify.com&timestamp=1587753486
```

So this part of the code:

```
    if(!event.queryStringParameters || !('shop' in event.queryStringParameters)){
        const response = {
            statusCode: 301,
            headers: {
                Location: action + '/install'
            }
        };
        return response;
    }
```

Is never called due to `shop` being in the queryStringParameters

**Comment by tvb** [comment]
@maxkostinevich why are you closing this without a comment?

**Comment by maxkostinevich** [comment]
@tvb just checked - the installation form works fine. If it does not work for you - feel free to fix it and send a PR.
